apiVersion: v1
kind: ConfigMap
metadata:
  name: django-db-configmap
  namespace: django-namespace
data:
  POSTGRES_DB: djangoPostsDB
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: django-db-secret
  namespace: django-namespace
type: Opaque
data:
  password: cG9zdGdyZXM=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: django-namespace
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: django-db-statefulset
  namespace: django-namespace
spec:
  serviceName: postgres-db-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: django-namespace
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: django-db-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-db-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: django-namespace
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432