apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
  namespace: django-namespace
data:
  POSTGRES_URL: db.django-namespace.svc.cluster.local
  POSTGRES_DB: djangoPostsDB
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-namespace
type: Opaque
data:
  password: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django-namespace
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: solunska/devops_project_image:latest
          name: django
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: password